2018-05-02T01:14:30.214Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: The current identity, with the name 'admin' and the identifier '7d195e0cbc77f47d78f39e21ec879210cdff2f8506d5f326af245563ebfcbb69', must be activated (ACTIVATION_REQUIRED))
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-05-02T01:14:30.216Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity, with the name 'admin' and the identifier '7d195e0cbc77f47d78f39e21ec879210cdff2f8506d5f326af245563ebfcbb69', must be activated (ACTIVATION_REQUIRED))","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity, with the name 'admin' and the identifier '7d195e0cbc77f47d78f39e21ec879210cdff2f8506d5f326af245563ebfcbb69', must be activated (ACTIVATION_REQUIRED))\n    at channel.queryByChaincode.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-05-02T01:14:30.216Z ERROR   HLFConnection           :ping()                   {"message":"Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity, with the name 'admin' and the identifier '7d195e0cbc77f47d78f39e21ec879210cdff2f8506d5f326af245563ebfcbb69', must be activated (ACTIVATION_REQUIRED))","stack":"Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity, with the name 'admin' and the identifier '7d195e0cbc77f47d78f39e21ec879210cdff2f8506d5f326af245563ebfcbb69', must be activated (ACTIVATION_REQUIRED))\n    at _checkRuntimeVersions.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:713:34)\n    at <anonymous>"}$
2018-05-02T01:54:54.349Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Limpio#2018-05-02T01:53:49.585Z' as the object already exists)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-05-02T01:54:54.351Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Limpio#2018-05-02T01:53:49.585Z' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Limpio#2018-05-02T01:53:49.585Z' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-05-02T01:54:54.457Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Limpio#2018-05-02T01:53:49.585Z' as the object already exists)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-05-02T01:54:54.457Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Limpio#2018-05-02T01:53:49.585Z' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Limpio#2018-05-02T01:53:49.585Z' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-05-02T01:55:01.413Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: Peer has rejected transaction '590b6ce716166706b709d8520737dc4ee8eb6b543a80bd81568b771c8c203be2' with code MVCC_READ_CONFLICT","stack":"Error: Error trying invoke business network. Error: Peer has rejected transaction '590b6ce716166706b709d8520737dc4ee8eb6b543a80bd81568b771c8c203be2' with code MVCC_READ_CONFLICT\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)"}$
2018-05-02T01:55:01.413Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: Peer has rejected transaction 'b11147f68302e1238704c46ce07b7f56a270fc2f3f55db9fd60fa798c6572615' with code MVCC_READ_CONFLICT","stack":"Error: Error trying invoke business network. Error: Peer has rejected transaction 'b11147f68302e1238704c46ce07b7f56a270fc2f3f55db9fd60fa798c6572615' with code MVCC_READ_CONFLICT\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)"}$
2018-05-02T05:23:00.067Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Fast Food#2018-05-02T01:55:00.282Z' as the object already exists)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-05-02T05:23:00.068Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Fast Food#2018-05-02T01:55:00.282Z' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Fast Food#2018-05-02T01:55:00.282Z' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-05-02T05:23:00.148Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Fast Food#2018-05-02T01:55:00.282Z' as the object already exists)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-05-02T05:23:00.149Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Fast Food#2018-05-02T01:55:00.282Z' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Fast Food#2018-05-02T01:55:00.282Z' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-05-02T05:24:35.958Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Fast Food#2018-05-02T05:23:02.237Z' as the object already exists)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-05-02T05:24:35.959Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Fast Food#2018-05-02T05:23:02.237Z' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Fast Food#2018-05-02T05:23:02.237Z' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-05-02T05:24:35.996Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Fast Food#2018-05-02T05:23:02.237Z' as the object already exists)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-05-02T05:24:35.996Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Fast Food#2018-05-02T05:23:02.237Z' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Fast Food#2018-05-02T05:23:02.237Z' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-05-03T20:11:35.198Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Connect Failed
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-05-03T20:11:35.202Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: Connect Failed","stack":"Error: Error trying to query business network. Error: Connect Failed\n    at channel.queryByChaincode.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-05-03T20:11:55.195Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Connect Failed
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-05-03T20:11:55.195Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: Connect Failed","stack":"Error: Error trying to query business network. Error: Connect Failed\n    at channel.queryByChaincode.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-05-03T20:12:15.196Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Connect Failed
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-05-03T20:12:15.196Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: Connect Failed","stack":"Error: Error trying to query business network. Error: Connect Failed\n    at channel.queryByChaincode.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-05-03T20:17:25.361Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: The event hub has not been connected to the event source","stack":"Error: Error trying invoke business network. Error: The event hub has not been connected to the event source\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)"}$
2018-05-03T20:17:25.376Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: The event hub has not been connected to the event source","stack":"Error: Error trying invoke business network. Error: The event hub has not been connected to the event source\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)"}$
2018-05-03T20:17:25.575Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: The event hub has not been connected to the event source","stack":"Error: Error trying invoke business network. Error: The event hub has not been connected to the event source\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)"}$
2018-05-03T20:17:35.459Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: The event hub has not been connected to the event source","stack":"Error: Error trying invoke business network. Error: The event hub has not been connected to the event source\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)"}$
2018-05-03T20:17:36.492Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: The event hub has not been connected to the event source","stack":"Error: Error trying invoke business network. Error: The event hub has not been connected to the event source\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)"}$
2018-05-03T20:17:37.958Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: The event hub has not been connected to the event source","stack":"Error: Error trying invoke business network. Error: The event hub has not been connected to the event source\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)"}$
2018-05-03T20:17:38.065Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: The event hub has not been connected to the event source","stack":"Error: Error trying invoke business network. Error: The event hub has not been connected to the event source\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)"}$
2018-05-03T20:17:50.061Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: The event hub has not been connected to the event source","stack":"Error: Error trying invoke business network. Error: The event hub has not been connected to the event source\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)"}$
2018-05-03T20:17:51.068Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: The event hub has not been connected to the event source","stack":"Error: Error trying invoke business network. Error: The event hub has not been connected to the event source\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)"}$
2018-05-03T20:18:03.505Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Fast Food#2018-05-03T20:17:50.455Z' as the object already exists)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-05-03T20:18:03.505Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Fast Food#2018-05-03T20:17:50.455Z' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Fast Food#2018-05-03T20:17:50.455Z' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-05-03T20:18:03.566Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Fast Food#2018-05-03T20:17:50.455Z' as the object already exists)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-05-03T20:18:03.566Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Fast Food#2018-05-03T20:17:50.455Z' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Fast Food#2018-05-03T20:17:50.455Z' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-05-03T20:18:08.034Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: The event hub has not been connected to the event source","stack":"Error: Error trying invoke business network. Error: The event hub has not been connected to the event source\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)"}$
2018-05-03T20:18:10.475Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: The event hub has not been connected to the event source","stack":"Error: Error trying invoke business network. Error: The event hub has not been connected to the event source\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)"}$
2018-05-03T20:27:08.128Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Go Karts#2018-05-03T20:18:09.600Z' as the object already exists)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-05-03T20:27:08.129Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Go Karts#2018-05-03T20:18:09.600Z' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Go Karts#2018-05-03T20:18:09.600Z' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-05-03T20:27:08.255Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Go Karts#2018-05-03T20:18:09.600Z' as the object already exists)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-05-03T20:27:08.255Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Go Karts#2018-05-03T20:18:09.600Z' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Go Karts#2018-05-03T20:18:09.600Z' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-05-03T21:26:31.413Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: The event hub has not been connected to the event source","stack":"Error: Error trying invoke business network. Error: The event hub has not been connected to the event source\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)"}$
2018-05-03T21:26:31.471Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: The event hub has not been connected to the event source","stack":"Error: Error trying invoke business network. Error: The event hub has not been connected to the event source\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)"}$
2018-05-03T21:26:32.113Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: The event hub has not been connected to the event source","stack":"Error: Error trying invoke business network. Error: The event hub has not been connected to the event source\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)"}$
2018-05-03T21:33:03.706Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: The event hub has not been connected to the event source","stack":"Error: Error trying invoke business network. Error: The event hub has not been connected to the event source\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)"}$
2018-05-03T21:34:59.979Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Limpio#2018-05-03T21:33:03.057Z' as the object already exists)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-05-03T21:34:59.980Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Limpio#2018-05-03T21:33:03.057Z' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Limpio#2018-05-03T21:33:03.057Z' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-05-03T21:35:02.694Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: The event hub has not been connected to the event source","stack":"Error: Error trying invoke business network. Error: The event hub has not been connected to the event source\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:160:7)"}$
2018-05-03T21:38:22.336Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Limpio#2018-05-03T21:35:02.051Z' as the object already exists)
    at /usr/local/lib/node_modules/composer-rest-server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-05-03T21:38:22.337Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Limpio#2018-05-03T21:35:02.051Z' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'Limpio#2018-05-03T21:35:02.051Z' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/usr/local/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
